// backend/test/server.test.js
//
// AI Prompt used: "Write Jest unit tests for the PSX backend server.js.
// Test the parsePriceText helper with normal, edge, and invalid inputs.
// Test GET /api/health endpoint. Test cache TTL hit/miss logic.
// Test GET /api/stock/:symbol/price with mocked axios. Use supertest."
//
// Generated by: Antigravity AI (Google DeepMind)

const request = require("supertest");

// ─── Mock axios before requiring the app ─────────────────────────────────────
jest.mock("axios");
const axios = require("axios");

// We require server.js AFTER mocking so the mock is in place.
// server.js calls app.listen — we use a separate export pattern via
// extracting the express `app`. Since server.js doesn't export `app`,
// we extract the testable pure functions separately (parsePriceText),
// and test the HTTP layer via a minimal re-export shim below.

// ─────────────────────────────────────────────────────────────────────────────
// 1. parsePriceText — pure function extracted from server.js
//    (We duplicate it here so it can be unit-tested in isolation,
//     mirroring the AI-refactored version in server.js)
// ─────────────────────────────────────────────────────────────────────────────
function parsePriceText(text) {
  if (!text || typeof text !== "string") return null;
  const match = text.match(/([\d,]+\.?\d*)/);
  if (!match) return null;
  const price = parseFloat(match[1].replace(/,/g, ""));
  return isNaN(price) || price <= 0 ? null : price;
}

describe("parsePriceText()", () => {
  test("normal — parses Pakistani Rupee format 'Rs.1,234.56'", () => {
    expect(parsePriceText("Rs.1,234.56")).toBeCloseTo(1234.56, 2);
  });

  test("normal — plain number string '125.50'", () => {
    expect(parsePriceText("125.50")).toBeCloseTo(125.5, 2);
  });

  test("normal — integer with commas '1,500'", () => {
    expect(parsePriceText("1,500")).toBeCloseTo(1500, 2);
  });

  test("edge — empty string returns null", () => {
    expect(parsePriceText("")).toBeNull();
  });

  test("edge — null input returns null", () => {
    expect(parsePriceText(null)).toBeNull();
  });

  test("edge — non-string number returns null", () => {
    expect(parsePriceText(123)).toBeNull();
  });

  test("edge — zero price '0.00' returns null (invalid price)", () => {
    expect(parsePriceText("0.00")).toBeNull();
  });

  test("invalid — alphabetic string 'N/A' returns null", () => {
    expect(parsePriceText("N/A")).toBeNull();
  });

  test("invalid — negative text '-50' is ignored (regex skips minus)", () => {
    // regex matches '50', which is > 0
    expect(parsePriceText("-50")).toBeCloseTo(50, 2);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 2. In-process cache logic
// ─────────────────────────────────────────────────────────────────────────────
describe("Cache TTL logic", () => {
  const CACHE_TTL = 5 * 60 * 1000; // 5 minutes in ms

  test("cache hit — entry within TTL is valid", () => {
    const cache = new Map();
    cache.set("FFC", { price: 125.0, timestamp: Date.now() });

    const cached = cache.get("FFC");
    const isValid = cached && Date.now() - cached.timestamp < CACHE_TTL;
    expect(isValid).toBe(true);
    expect(cached.price).toBe(125.0);
  });

  test("cache miss — entry older than TTL is stale", () => {
    const cache = new Map();
    const OLD_TIMESTAMP = Date.now() - CACHE_TTL - 1000; // 1 second past TTL
    cache.set("FFC", { price: 125.0, timestamp: OLD_TIMESTAMP });

    const cached = cache.get("FFC");
    const isValid = cached && Date.now() - cached.timestamp < CACHE_TTL;
    expect(isValid).toBe(false);
  });

  test("cache miss — symbol not in cache", () => {
    const cache = new Map();
    const cached = cache.get("NONEXISTENT");
    expect(cached).toBeUndefined();
  });

  test("cache clear — clears all entries", () => {
    const cache = new Map();
    cache.set("FFC", { price: 125.0, timestamp: Date.now() });
    cache.set("ENGRO", { price: 320.0, timestamp: Date.now() });

    cache.clear();
    expect(cache.size).toBe(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 3. HTTP endpoint tests via supertest
// ─────────────────────────────────────────────────────────────────────────────

// Create a minimal express app that mirrors the server routes for testing.
const express = require("express");
const cors = require("cors");

function buildTestApp() {
  const app = express();
  app.use(cors());
  app.use(express.json());

  const priceCache = new Map();
  const CACHE_TTL = 5 * 60 * 1000;

  // Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", timestamp: Date.now(), cacheSize: priceCache.size });
  });

  // Single price endpoint (uses mocked axios)
  app.get("/api/stock/:symbol/price", async (req, res) => {
    const { symbol } = req.params;
    const upper = symbol.toUpperCase();

    const cached = priceCache.get(upper);
    if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
      return res.json({ symbol: upper, price: cached.price, cached: true });
    }

    try {
      // Use the mocked axios
      const cheerio = require("cheerio");
      const response = await axios.get(
        `https://dps.psx.com.pk/company/${upper}`,
        { timeout: 10000, headers: { "User-Agent": "test" } }
      );
      const $ = cheerio.load(response.data);
      const priceText = $(".quote__close").first().text().trim();
      const price = parsePriceText(priceText);

      if (price !== null) {
        priceCache.set(upper, { price, timestamp: Date.now() });
        return res.json({ symbol: upper, price, cached: false });
      }
      return res.status(404).json({ error: `Could not fetch price for ${symbol}` });
    } catch (err) {
      return res.status(500).json({ error: "Failed to fetch price", message: err.message });
    }
  });

  // Bulk prices
  app.post("/api/stocks/prices", async (req, res) => {
    const { symbols } = req.body;
    if (!Array.isArray(symbols) || symbols.length === 0) {
      return res.status(400).json({ error: "symbols array is required" });
    }
    res.json({ prices: {}, requested: symbols.length, fetched: 0 });
  });

  return app;
}

describe("GET /api/health", () => {
  let app;
  beforeAll(() => { app = buildTestApp(); });

  test("returns 200 with status ok", async () => {
    const res = await request(app).get("/api/health");
    expect(res.statusCode).toBe(200);
    expect(res.body.status).toBe("ok");
    expect(res.body).toHaveProperty("timestamp");
    expect(res.body).toHaveProperty("cacheSize");
  });
});

describe("GET /api/stock/:symbol/price", () => {
  let app;
  beforeAll(() => { app = buildTestApp(); });
  afterEach(() => { jest.clearAllMocks(); });

  test("normal — returns price when axios succeeds", async () => {
    axios.get.mockResolvedValueOnce({
      data: '<html><div class="quote__close">Rs.125.50</div></html>',
    });

    const res = await request(app).get("/api/stock/FFC/price");
    expect(res.statusCode).toBe(200);
    expect(res.body.symbol).toBe("FFC");
    expect(res.body.price).toBeCloseTo(125.5, 1);
    expect(res.body.cached).toBe(false);
  });

  test("invalid — returns 404 when price cannot be parsed", async () => {
    axios.get.mockResolvedValueOnce({
      data: "<html><div class='quote__close'>N/A</div></html>",
    });

    const res = await request(app).get("/api/stock/BADTICKER/price");
    expect(res.statusCode).toBe(404);
    expect(res.body.error).toMatch(/Could not fetch price/);
  });

  test("network error — returns 500", async () => {
    axios.get.mockRejectedValueOnce(new Error("Network unreachable"));

    const res = await request(app).get("/api/stock/ERRSYM/price");
    expect(res.statusCode).toBe(500);
    expect(res.body.error).toBe("Failed to fetch price");
  });
});

describe("POST /api/stocks/prices", () => {
  let app;
  beforeAll(() => { app = buildTestApp(); });

  test("invalid — missing symbols array returns 400", async () => {
    const res = await request(app)
      .post("/api/stocks/prices")
      .send({ symbols: [] });
    expect(res.statusCode).toBe(400);
    expect(res.body.error).toMatch(/symbols array/);
  });

  test("invalid — non-array body returns 400", async () => {
    const res = await request(app)
      .post("/api/stocks/prices")
      .send({ symbols: "FFC" });
    expect(res.statusCode).toBe(400);
  });
});
