import 'models.dart';

const String defaultBackendHost = 'http://localhost:3001';

final List<String> defaultFavorites = ['FFC', 'HUBC', 'MEBL'];

final List<PortfolioItem> defaultPortfolio = [
  PortfolioItem(
    symbol: 'FFC',
    name: 'Fauji Fertilizer Co',
    sector: 'Fertilizer',
    tier: 'core',
    shares: 27,
    avgBuy: 520.99,
    dpshist: 55,
  ),
  PortfolioItem(
    symbol: 'BIPL',
    name: 'BankIslami Pakistan',
    sector: 'Banking',
    tier: 'small',
    shares: 100,
    avgBuy: 26.74,
    dpshist: 1.5,
  ),
  PortfolioItem(
    symbol: 'HUBC',
    name: 'Hub Power Company',
    sector: 'Energy',
    tier: 'core',
    shares: 31,
    avgBuy: 219.51,
    dpshist: 20,
  ),
  PortfolioItem(
    symbol: 'NATF',
    name: 'National Foods Limited',
    sector: 'Food',
    tier: 'small',
    shares: 15,
    avgBuy: 379.38,
    dpshist: 18,
  ),
  PortfolioItem(
    symbol: 'OGDC',
    name: 'Oil & Gas Dev Co',
    sector: 'Energy',
    tier: 'secondary',
    shares: 19,
    avgBuy: 309.77,
    dpshist: 22,
  ),
  PortfolioItem(
    symbol: 'EFERT',
    name: 'Engro Fertilizers',
    sector: 'Fertilizer',
    tier: 'core',
    shares: 63,
    avgBuy: 204.57,
    dpshist: 20,
  ),
  PortfolioItem(
    symbol: 'FATIMA',
    name: 'Fatima Fertilizer Co',
    sector: 'Fertilizer',
    tier: 'small',
    shares: 21,
    avgBuy: 141.86,
    dpshist: 12,
  ),
  PortfolioItem(
    symbol: 'MEBL',
    name: 'Meezan Bank',
    sector: 'Banking',
    tier: 'small',
    shares: 10,
    avgBuy: 477.60,
    dpshist: 15,
  ),
  PortfolioItem(
    symbol: 'PPL',
    name: 'Pakistan Petroleum Ltd',
    sector: 'Energy',
    tier: 'secondary',
    shares: 7,
    avgBuy: 204.99,
    dpshist: 17,
  ),
];

final List<Stock> stockDb = [
  Stock(
    symbol: 'FFC',
    name: 'Fauji Fertilizer Co',
    sector: 'Fertilizer',
    price: 504.27,
    dividendYield: 10.9,
    marketCap: '150B',
    volume: '2.1M',
    change: '-2.1%',
    de: 0.8,
    icr: 12.1,
    netDebtEbitda: 0.5,
    assetTurnover: 1.1,
    invTurnover: 8.2,
    pfcf: 9.2,
    fcfYield: 10.8,
    ocfRatio: 1.4,
    brScore: 82,
    verdict: 'Strong',
  ),
  Stock(
    symbol: 'BIPL',
    name: 'BankIslami Pakistan',
    sector: 'Banking',
    price: 24.98,
    dividendYield: 6.0,
    marketCap: '50B',
    volume: '5.2M',
    change: '+1.2%',
    de: null,
    icr: null,
    netDebtEbitda: null,
    assetTurnover: 0.08,
    invTurnover: null,
    pfcf: 7.8,
    fcfYield: 9.2,
    ocfRatio: 0.9,
    brScore: 61,
    verdict: 'Caution',
  ),
  Stock(
    symbol: 'HUBC',
    name: 'Hub Power Company',
    sector: 'Energy',
    price: 220.49,
    dividendYield: 9.1,
    marketCap: '280B',
    volume: '1.8M',
    change: '+0.5%',
    de: 1.2,
    icr: 6.8,
    netDebtEbitda: 1.8,
    assetTurnover: 0.7,
    invTurnover: null,
    pfcf: 11.4,
    fcfYield: 8.8,
    ocfRatio: 1.2,
    brScore: 75,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'NATF',
    name: 'National Foods Limited',
    sector: 'Food',
    price: 370.08,
    dividendYield: 4.9,
    marketCap: '45B',
    volume: '0.3M',
    change: '-0.8%',
    de: 0.7,
    icr: 6.4,
    netDebtEbitda: 1.9,
    assetTurnover: 1.6,
    invTurnover: 6.8,
    pfcf: 16.3,
    fcfYield: 6.1,
    ocfRatio: 0.8,
    brScore: 58,
    verdict: 'Caution',
  ),
  Stock(
    symbol: 'OGDC',
    name: 'Oil & Gas Dev Co',
    sector: 'Energy',
    price: 303.17,
    dividendYield: 7.3,
    marketCap: '480B',
    volume: '3.1M',
    change: '+2.3%',
    de: 0.1,
    icr: 28.5,
    netDebtEbitda: -0.2,
    assetTurnover: 0.5,
    invTurnover: null,
    pfcf: 7.3,
    fcfYield: 13.7,
    ocfRatio: 2.1,
    brScore: 91,
    verdict: 'Excellent',
  ),
  Stock(
    symbol: 'EFERT',
    name: 'Engro Fertilizers',
    sector: 'Fertilizer',
    price: 198.83,
    dividendYield: 10.1,
    marketCap: '110B',
    volume: '2.8M',
    change: '+0.9%',
    de: 0.6,
    icr: 15.3,
    netDebtEbitda: 0.3,
    assetTurnover: 1.3,
    invTurnover: 9.1,
    pfcf: 8.1,
    fcfYield: 12.3,
    ocfRatio: 1.6,
    brScore: 88,
    verdict: 'Excellent',
  ),
  Stock(
    symbol: 'FATIMA',
    name: 'Fatima Fertilizer Co',
    sector: 'Fertilizer',
    price: 130.29,
    dividendYield: 9.2,
    marketCap: '65B',
    volume: '1.5M',
    change: '-1.1%',
    de: 0.9,
    icr: 8.2,
    netDebtEbitda: 1.1,
    assetTurnover: 1.0,
    invTurnover: 7.4,
    pfcf: 10.2,
    fcfYield: 11.8,
    ocfRatio: 1.3,
    brScore: 74,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'MEBL',
    name: 'Meezan Bank',
    sector: 'Banking',
    price: 492.34,
    dividendYield: 3.0,
    marketCap: '85B',
    volume: '0.8M',
    change: '+0.3%',
    de: null,
    icr: null,
    netDebtEbitda: null,
    assetTurnover: 0.1,
    invTurnover: null,
    pfcf: 13.1,
    fcfYield: 7.7,
    ocfRatio: 1.1,
    brScore: 72,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'PPL',
    name: 'Pakistan Petroleum Ltd',
    sector: 'Energy',
    price: 206.64,
    dividendYield: 8.2,
    marketCap: '120B',
    volume: '1.2M',
    change: '+1.7%',
    de: 0.2,
    icr: 22.1,
    netDebtEbitda: 0.1,
    assetTurnover: 0.6,
    invTurnover: null,
    pfcf: 8.8,
    fcfYield: 11.4,
    ocfRatio: 1.8,
    brScore: 87,
    verdict: 'Strong',
  ),
  Stock(
    symbol: 'ENGRO',
    name: 'Engro Corporation',
    sector: 'Conglomerate',
    price: 330.40,
    dividendYield: 9.5,
    marketCap: '180B',
    volume: '1.1M',
    change: '+0.8%',
    de: 0.8,
    icr: 8.5,
    netDebtEbitda: 0.8,
    assetTurnover: 0.9,
    invTurnover: 6.5,
    pfcf: 10.5,
    fcfYield: 11.2,
    ocfRatio: 1.3,
    brScore: 80,
    verdict: 'Strong',
  ),
  Stock(
    symbol: 'LUCK',
    name: 'Lucky Cement',
    sector: 'Cement',
    price: 765.20,
    dividendYield: 4.2,
    marketCap: '240B',
    volume: '0.9M',
    change: '+1.4%',
    de: 0.4,
    icr: 12.5,
    netDebtEbitda: 0.2,
    assetTurnover: 1.1,
    invTurnover: 7.2,
    pfcf: 14.2,
    fcfYield: 8.5,
    ocfRatio: 1.5,
    brScore: 71,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'SYS',
    name: 'Systems Limited',
    sector: 'Technology',
    price: 410.80,
    dividendYield: 2.5,
    marketCap: '120B',
    volume: '2.5M',
    change: '-1.2%',
    de: 0.1,
    icr: 25.4,
    netDebtEbitda: 0.05,
    assetTurnover: 1.4,
    invTurnover: null,
    pfcf: 22.4,
    fcfYield: 6.8,
    ocfRatio: 1.2,
    brScore: 68,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'PSO',
    name: 'Pakistan State Oil',
    sector: 'Energy',
    price: 185.30,
    dividendYield: 8.0,
    marketCap: '87B',
    volume: '3.4M',
    change: '+1.1%',
    de: 1.1,
    icr: 4.2,
    netDebtEbitda: 1.4,
    assetTurnover: 2.1,
    invTurnover: 12.4,
    pfcf: 8.5,
    fcfYield: 9.4,
    ocfRatio: 1.1,
    brScore: 73,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'MCB',
    name: 'MCB Bank Limited',
    sector: 'Banking',
    price: 210.40,
    dividendYield: 9.8,
    marketCap: '250B',
    volume: '1.8M',
    change: '+0.5%',
    de: null,
    icr: null,
    netDebtEbitda: null,
    assetTurnover: 0.09,
    invTurnover: null,
    pfcf: 8.2,
    fcfYield: 9.1,
    ocfRatio: 1.1,
    brScore: 79,
    verdict: 'Strong',
  ),
  Stock(
    symbol: 'HBL',
    name: 'Habib Bank Limited',
    sector: 'Banking',
    price: 118.50,
    dividendYield: 7.8,
    marketCap: '173B',
    volume: '4.2M',
    change: '-0.3%',
    de: null,
    icr: null,
    netDebtEbitda: null,
    assetTurnover: 0.07,
    invTurnover: null,
    pfcf: 9.1,
    fcfYield: 8.4,
    ocfRatio: 1.0,
    brScore: 70,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'FFBL',
    name: 'Fauji Fertilizer Bin Qasim',
    sector: 'Fertilizer',
    price: 38.40,
    dividendYield: 7.5,
    marketCap: '49B',
    volume: '8.4M',
    change: '+2.1%',
    de: 1.3,
    icr: 4.8,
    netDebtEbitda: 1.9,
    assetTurnover: 1.2,
    invTurnover: 8.5,
    pfcf: 7.9,
    fcfYield: 10.1,
    ocfRatio: 1.1,
    brScore: 72,
    verdict: 'Good',
  ),
  Stock(
    symbol: 'SEARL',
    name: 'The Searle Company',
    sector: 'Pharmaceuticals',
    price: 58.60,
    dividendYield: 3.5,
    marketCap: '22B',
    volume: '2.1M',
    change: '-0.8%',
    de: 0.8,
    icr: 3.2,
    netDebtEbitda: 2.2,
    assetTurnover: 0.8,
    invTurnover: 4.2,
    pfcf: 18.4,
    fcfYield: 5.2,
    ocfRatio: 0.9,
    brScore: 54,
    verdict: 'Caution',
  ),
  Stock(
    symbol: 'MARI',
    name: 'Mari Petroleum',
    sector: 'Energy',
    price: 2450.00,
    dividendYield: 6.5,
    marketCap: '326B',
    volume: '0.1M',
    change: '+1.8%',
    de: 0.15,
    icr: 32.4,
    netDebtEbitda: -0.1,
    assetTurnover: 0.8,
    invTurnover: null,
    pfcf: 9.8,
    fcfYield: 12.1,
    ocfRatio: 2.3,
    brScore: 89,
    verdict: 'Excellent',
  ),
  Stock(
    symbol: 'TRG',
    name: 'TRG Pakistan',
    sector: 'Technology',
    price: 65.40,
    dividendYield: 0.0,
    marketCap: '35B',
    volume: '6.8M',
    change: '-3.4%',
    de: 1.8,
    icr: 1.2,
    netDebtEbitda: 4.2,
    assetTurnover: 0.4,
    invTurnover: null,
    pfcf: 45.0,
    fcfYield: 2.1,
    ocfRatio: 0.4,
    brScore: 35,
    verdict: 'Avoid',
  ),
];
