/// PortfolioCalculator — AI-generated utility class
///
/// Prompt used: "Generate a Dart utility class called PortfolioCalculator
/// that computes gain/loss percentage, yield-on-cost, weighted average cost,
/// and a portfolio diversification score from a list of PortfolioItem objects.
/// Include null safety, clear documentation, and pure functions only."
///
/// Generated by: Antigravity AI (Google DeepMind)
library portfolio_calculator;

import 'models.dart';

/// Pure utility class providing portfolio financial calculations.
/// All methods are static and have no side effects.
class PortfolioCalculator {
  PortfolioCalculator._(); // prevent instantiation

  // ─────────────────────────────────────────────────────────────────────────
  // Gain / Loss
  // ─────────────────────────────────────────────────────────────────────────

  /// Returns the absolute gain or loss for a single [item] given its
  /// [currentPrice]. Positive → profit, negative → loss.
  ///
  /// Formula: (currentPrice − avgBuy) × shares
  static double gainLoss(PortfolioItem item, double currentPrice) {
    return (currentPrice - item.avgBuy) * item.shares;
  }

  /// Returns the gain/loss as a percentage relative to cost basis.
  ///
  /// Returns `0.0` if cost basis is zero to avoid division by zero.
  ///
  /// Formula: ((currentPrice − avgBuy) / avgBuy) × 100
  static double gainLossPercent(PortfolioItem item, double currentPrice) {
    if (item.avgBuy <= 0) return 0.0;
    return ((currentPrice - item.avgBuy) / item.avgBuy) * 100.0;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Yield on Cost
  // ─────────────────────────────────────────────────────────────────────────

  /// Returns the yield-on-cost for an [item]: the annual dividend income
  /// per share ([item.dpshist]) as a percentage of the average buy price.
  ///
  /// Returns `0.0` if avgBuy is zero.
  ///
  /// Formula: (dpshist / avgBuy) × 100
  static double yieldOnCost(PortfolioItem item) {
    if (item.avgBuy <= 0) return 0.0;
    return (item.dpshist / item.avgBuy) * 100.0;
  }

  /// Returns the portfolio-level blended yield-on-cost, weighted by cost basis.
  ///
  /// Returns `0.0` for an empty portfolio or zero total cost.
  static double blendedYieldOnCost(List<PortfolioItem> portfolio) {
    if (portfolio.isEmpty) return 0.0;
    double totalCost = 0.0;
    double totalAnnualIncome = 0.0;
    for (final item in portfolio) {
      final cost = item.avgBuy * item.shares;
      totalCost += cost;
      totalAnnualIncome += item.dpshist * item.shares;
    }
    if (totalCost <= 0) return 0.0;
    return (totalAnnualIncome / totalCost) * 100.0;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Weighted Average Cost
  // ─────────────────────────────────────────────────────────────────────────

  /// Computes the weighted average cost of the entire [portfolio].
  ///
  /// Returns `0.0` for an empty portfolio or zero total shares.
  static double weightedAverageCost(List<PortfolioItem> portfolio) {
    if (portfolio.isEmpty) return 0.0;
    double totalCost = 0.0;
    int totalShares = 0;
    for (final item in portfolio) {
      totalCost += item.avgBuy * item.shares;
      totalShares += item.shares;
    }
    if (totalShares == 0) return 0.0;
    return totalCost / totalShares;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Diversification Score
  // ─────────────────────────────────────────────────────────────────────────

  /// Computes a portfolio diversification score from `0` to `100`.
  ///
  /// The score is based on the Herfindahl–Hirschman Index (HHI), inverted so
  /// that a perfectly concentrated (single-stock) portfolio scores `0` and a
  /// perfectly diversified portfolio approaches `100`.
  ///
  /// Score = (1 − HHI) × 100
  /// where HHI = Σ(weight_i²) and weight_i = cost_i / totalCost.
  ///
  /// Returns `0.0` for empty portfolios or a single holding.
  static double diversificationScore(List<PortfolioItem> portfolio) {
    if (portfolio.length <= 1) return 0.0;

    final totalCost = portfolio.fold<double>(
      0.0,
      (sum, item) => sum + item.avgBuy * item.shares,
    );
    if (totalCost <= 0) return 0.0;

    double hhi = 0.0;
    for (final item in portfolio) {
      final weight = (item.avgBuy * item.shares) / totalCost;
      hhi += weight * weight;
    }

    return (1.0 - hhi) * 100.0;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Total Market Value
  // ─────────────────────────────────────────────────────────────────────────

  /// Computes total market value of the portfolio given a map of
  /// [symbol → currentPrice]. Items missing from the map fall back to avgBuy.
  static double totalMarketValue(
    List<PortfolioItem> portfolio,
    Map<String, double> prices,
  ) {
    return portfolio.fold(0.0, (sum, item) {
      final price = prices[item.symbol] ?? item.avgBuy;
      return sum + price * item.shares;
    });
  }
}
