// test/unit/models_test.dart
//
// AI Prompt used: "Write comprehensive Flutter unit tests for Stock.fromJson()
// and PortfolioItem.fromJson() covering normal data, missing/null fields,
// string-encoded numbers, edge cases like zero shares, and invalid JSON values."
//
// Generated by: Antigravity AI (Google DeepMind)

import 'package:flutter_test/flutter_test.dart';
import 'package:psx_dividend_machine/models.dart';

void main() {
  // ═══════════════════════════════════════════════════════════════════════════
  // Stock.fromJson()
  // ═══════════════════════════════════════════════════════════════════════════
  group('Stock.fromJson()', () {
    test('normal — parses all fields correctly', () {
      final json = {
        'symbol': 'FFC',
        'name': 'Fauji Fertilizer Company',
        'sector': 'Fertilizer',
        'price': 125.50,
        'yield': 8.5,
        'marketCap': '75B',
        'volume': '2.1M',
        'change': '+1.2%',
        'de': 0.45,
        'icr': 12.0,
        'brScore': 7,
        'verdict': 'BUY',
      };

      final stock = Stock.fromJson(json);

      expect(stock.symbol, 'FFC');
      expect(stock.name, 'Fauji Fertilizer Company');
      expect(stock.sector, 'Fertilizer');
      expect(stock.price, 125.50);
      expect(stock.dividendYield, 8.5);
      expect(stock.marketCap, '75B');
      expect(stock.volume, '2.1M');
      expect(stock.brScore, 7);
      expect(stock.verdict, 'BUY');
      expect(stock.de, 0.45);
      expect(stock.icr, 12.0);
    });

    test('missing optional fields — defaults to null or empty string', () {
      final json = {
        'symbol': 'BIPL',
        'name': 'BankIslami Pakistan',
        'sector': 'Banking',
        'price': 45.0,
      };

      final stock = Stock.fromJson(json);

      expect(stock.symbol, 'BIPL');
      expect(stock.price, 45.0);
      expect(stock.dividendYield, isNull);
      expect(stock.de, isNull);
      expect(stock.icr, isNull);
      expect(stock.brScore, isNull);
      expect(stock.marketCap, '');
      expect(stock.verdict, '');
    });

    test('price as string — parses correctly', () {
      final json = {
        'symbol': 'ENGRO',
        'name': 'Engro Corporation',
        'sector': 'Diversified',
        'price': '320.75',
      };

      final stock = Stock.fromJson(json);
      expect(stock.price, 320.75);
    });

    test('null fields — replaced with safe defaults', () {
      final json = {
        'symbol': null,
        'name': null,
        'sector': null,
        'price': null,
        'yield': null,
        'brScore': null,
      };

      final stock = Stock.fromJson(json);

      expect(stock.symbol, '');
      expect(stock.name, '');
      expect(stock.sector, '');
      expect(stock.price, 0.0);
      expect(stock.dividendYield, isNull);
      expect(stock.brScore, isNull);
    });

    test('brScore as string — parsed to int', () {
      final json = {
        'symbol': 'MCB',
        'name': 'MCB Bank',
        'sector': 'Banking',
        'price': 210.0,
        'brScore': '9',
      };

      final stock = Stock.fromJson(json);
      expect(stock.brScore, 9);
    });

    test('invalid brScore string — parsed as null', () {
      final json = {
        'symbol': 'UBL',
        'name': 'United Bank',
        'sector': 'Banking',
        'price': 180.0,
        'brScore': 'invalid',
      };

      final stock = Stock.fromJson(json);
      expect(stock.brScore, isNull);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // PortfolioItem.fromJson()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioItem.fromJson()', () {
    test('normal — all fields parsed correctly', () {
      final json = {
        'symbol': 'FFC',
        'name': 'Fauji Fertilizer Company',
        'sector': 'Fertilizer',
        'tier': 'core',
        'shares': 500,
        'avgBuy': 112.50,
        'dpshist': 10.0,
      };

      final item = PortfolioItem.fromJson(json);

      expect(item.symbol, 'FFC');
      expect(item.shares, 500);
      expect(item.avgBuy, 112.50);
      expect(item.dpshist, 10.0);
      expect(item.tier, 'core');
    });

    test('shares as string — parsed to int', () {
      final json = {
        'symbol': 'ENGRO',
        'name': 'Engro',
        'sector': 'Diversified',
        'tier': 'small',
        'shares': '200',
        'avgBuy': 300.0,
        'dpshist': 15.0,
      };

      final item = PortfolioItem.fromJson(json);
      expect(item.shares, 200);
    });

    test('zero shares — allowed (edge case)', () {
      final json = {
        'symbol': 'TEST',
        'name': 'Test Stock',
        'sector': 'Unknown',
        'tier': 'small',
        'shares': 0,
        'avgBuy': 100.0,
        'dpshist': 5.0,
      };

      final item = PortfolioItem.fromJson(json);
      expect(item.shares, 0);
    });

    test('null fields — defaults to empty strings and zeros', () {
      final json = {
        'symbol': null,
        'name': null,
        'sector': null,
        'tier': null,
        'shares': null,
        'avgBuy': null,
        'dpshist': null,
      };

      final item = PortfolioItem.fromJson(json);

      expect(item.symbol, '');
      expect(item.shares, 0);
      expect(item.avgBuy, 0.0);
      expect(item.dpshist, 0.0);
    });

    test('avgBuy as string — parsed to double', () {
      final json = {
        'symbol': 'LUCK',
        'name': 'Lucky Cement',
        'sector': 'Cement',
        'tier': 'core',
        'shares': 100,
        'avgBuy': '850.25',
        'dpshist': '20.5',
      };

      final item = PortfolioItem.fromJson(json);
      expect(item.avgBuy, 850.25);
      expect(item.dpshist, 20.5);
    });
  });
}
