// test/unit/portfolio_calculator_test.dart
//
// AI Prompt used: "Write Flutter unit tests for PortfolioCalculator covering
// gainLoss, gainLossPercent, yieldOnCost, blendedYieldOnCost,
// weightedAverageCost, diversificationScore, and totalMarketValue.
// Include normal, edge (zero/empty), and boundary cases."
//
// Generated by: Antigravity AI (Google DeepMind)

import 'package:flutter_test/flutter_test.dart';
import 'package:psx_dividend_machine/models.dart';
import 'package:psx_dividend_machine/portfolio_calculator.dart';

/// Creates a minimal [PortfolioItem] for testing.
PortfolioItem makeItem({
  String symbol = 'TEST',
  int shares = 100,
  double avgBuy = 100.0,
  double dpshist = 10.0,
}) {
  return PortfolioItem(
    symbol: symbol,
    name: symbol,
    sector: 'Test',
    tier: 'small',
    shares: shares,
    avgBuy: avgBuy,
    dpshist: dpshist,
  );
}

void main() {
  // ═══════════════════════════════════════════════════════════════════════════
  // gainLoss()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioCalculator.gainLoss()', () {
    test('normal — positive gain', () {
      final item = makeItem(shares: 200, avgBuy: 100.0);
      expect(PortfolioCalculator.gainLoss(item, 120.0), closeTo(4000.0, 0.001));
    });

    test('normal — negative loss', () {
      final item = makeItem(shares: 100, avgBuy: 150.0);
      expect(PortfolioCalculator.gainLoss(item, 100.0), closeTo(-5000.0, 0.001));
    });

    test('edge — current price equals avgBuy', () {
      final item = makeItem(shares: 500, avgBuy: 75.0);
      expect(PortfolioCalculator.gainLoss(item, 75.0), closeTo(0.0, 0.001));
    });

    test('edge — zero shares', () {
      final item = makeItem(shares: 0, avgBuy: 100.0);
      expect(PortfolioCalculator.gainLoss(item, 150.0), closeTo(0.0, 0.001));
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // gainLossPercent()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioCalculator.gainLossPercent()', () {
    test('normal — 20% gain', () {
      final item = makeItem(avgBuy: 100.0);
      expect(
        PortfolioCalculator.gainLossPercent(item, 120.0),
        closeTo(20.0, 0.001),
      );
    });

    test('normal — 50% loss', () {
      final item = makeItem(avgBuy: 200.0);
      expect(
        PortfolioCalculator.gainLossPercent(item, 100.0),
        closeTo(-50.0, 0.001),
      );
    });

    test('edge — zero avgBuy returns 0.0 (no division by zero)', () {
      final item = makeItem(avgBuy: 0.0);
      expect(PortfolioCalculator.gainLossPercent(item, 100.0), 0.0);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // yieldOnCost()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioCalculator.yieldOnCost()', () {
    test('normal — 10% yield on cost', () {
      final item = makeItem(avgBuy: 100.0, dpshist: 10.0);
      expect(PortfolioCalculator.yieldOnCost(item), closeTo(10.0, 0.001));
    });

    test('normal — fractional yield', () {
      final item = makeItem(avgBuy: 120.0, dpshist: 9.0);
      expect(PortfolioCalculator.yieldOnCost(item), closeTo(7.5, 0.001));
    });

    test('edge — zero avgBuy returns 0.0', () {
      final item = makeItem(avgBuy: 0.0, dpshist: 10.0);
      expect(PortfolioCalculator.yieldOnCost(item), 0.0);
    });

    test('edge — zero dpshist returns 0.0', () {
      final item = makeItem(avgBuy: 100.0, dpshist: 0.0);
      expect(PortfolioCalculator.yieldOnCost(item), 0.0);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // weightedAverageCost()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioCalculator.weightedAverageCost()', () {
    test('single holding', () {
      final portfolio = [makeItem(shares: 100, avgBuy: 50.0)];
      expect(
        PortfolioCalculator.weightedAverageCost(portfolio),
        closeTo(50.0, 0.001),
      );
    });

    test('two equal-size holdings', () {
      final portfolio = [
        makeItem(symbol: 'A', shares: 100, avgBuy: 100.0),
        makeItem(symbol: 'B', shares: 100, avgBuy: 200.0),
      ];
      expect(
        PortfolioCalculator.weightedAverageCost(portfolio),
        closeTo(150.0, 0.001),
      );
    });

    test('two unequal-size holdings', () {
      final portfolio = [
        makeItem(symbol: 'A', shares: 300, avgBuy: 100.0), // cost = 30 000
        makeItem(symbol: 'B', shares: 100, avgBuy: 200.0), // cost = 20 000
      ];
      // WAC = 50 000 / 400 = 125
      expect(
        PortfolioCalculator.weightedAverageCost(portfolio),
        closeTo(125.0, 0.001),
      );
    });

    test('empty portfolio returns 0.0', () {
      expect(PortfolioCalculator.weightedAverageCost([]), 0.0);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // diversificationScore()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioCalculator.diversificationScore()', () {
    test('single holding — score is 0.0', () {
      final portfolio = [makeItem()];
      expect(PortfolioCalculator.diversificationScore(portfolio), 0.0);
    });

    test('two equal holdings — score ≈ 50', () {
      final portfolio = [
        makeItem(symbol: 'A', shares: 100, avgBuy: 100.0),
        makeItem(symbol: 'B', shares: 100, avgBuy: 100.0),
      ];
      // HHI = 0.5² + 0.5² = 0.5 → score = 50
      expect(
        PortfolioCalculator.diversificationScore(portfolio),
        closeTo(50.0, 0.01),
      );
    });

    test('four equal holdings — score ≈ 75', () {
      final portfolio = List.generate(
        4,
        (i) => makeItem(symbol: 'S$i', shares: 100, avgBuy: 100.0),
      );
      // HHI = 4 × 0.25² = 0.25 → score = 75
      expect(
        PortfolioCalculator.diversificationScore(portfolio),
        closeTo(75.0, 0.01),
      );
    });

    test('empty portfolio returns 0.0', () {
      expect(PortfolioCalculator.diversificationScore([]), 0.0);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // totalMarketValue()
  // ═══════════════════════════════════════════════════════════════════════════
  group('PortfolioCalculator.totalMarketValue()', () {
    test('normal — uses provided prices', () {
      final portfolio = [
        makeItem(symbol: 'FFC', shares: 100, avgBuy: 100.0),
        makeItem(symbol: 'ENGRO', shares: 50, avgBuy: 300.0),
      ];
      final prices = {'FFC': 120.0, 'ENGRO': 350.0};
      // 100 × 120 + 50 × 350 = 12 000 + 17 500 = 29 500
      expect(
        PortfolioCalculator.totalMarketValue(portfolio, prices),
        closeTo(29500.0, 0.001),
      );
    });

    test('missing price — falls back to avgBuy', () {
      final portfolio = [
        makeItem(symbol: 'LUCK', shares: 200, avgBuy: 850.0),
      ];
      // No price provided → fallback to avgBuy 850
      expect(
        PortfolioCalculator.totalMarketValue(portfolio, {}),
        closeTo(170000.0, 0.001),
      );
    });

    test('empty portfolio returns 0.0', () {
      expect(
        PortfolioCalculator.totalMarketValue([], {'FFC': 100.0}),
        0.0,
      );
    });
  });
}
